openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: Successful response
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Title:
                  type: string
                  required: true
                Description:
                  type: string
                Priority:
                  type: string
                  enum: [Low, Medium, High]
                CreatedBy:
                  type: string
                Status:
                  type: string
                  enum: [ToDo, In Progress, Completed]
                DeletedAt:
                  type: string
                Deadline:
                  type: string
      responses:
        '200':
          description: Successful response
  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
    put:
      summary: Update a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Successful response
  /tasks/softDelete/{id}:
    put:
      summary: Soft delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
components:
  schemas:
    Task:
      type: object
      properties:
        Title:
          type: string
          required: true
        Description:
          type: string
        Priority:
          type: string
          enum: [Low, Medium, High]
        CreatedBy:
          type: string
        Status:
          type: string
          enum: [ToDo, In Progress, Completed]
        DeletedAt:
          type: string
        Deadline:
          type: string
